apiVersion: apps/v1
kind: Deployment
metadata:
  name: homemenuplanner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homemenuplanner
  template:
    metadata:
      labels:
        app: homemenuplanner
    spec:
      containers:
        - name: homemenuplanner
          image: rmstruthers1/homemenuplanner:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CORS_ALLOWED_ORIGIN
              value: "http://homemenuplanner-frontend.s3-website-us-east-1.amazonaws.com"
            - name: JWT_COOKIE_SECURE
              value: "true"
            - name: JWT_COOKIE_SAME_SITE
              value: "None"
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: jdbc-url
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: username
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: jwt-secret
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: homemenuplanner-service
spec:
  selector:
    app: homemenuplanner
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer
