apiVersion: apps/v1
kind: Deployment
metadata:
  name: homemenuplanner-deployment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:777605092423:certificate/ce0aee3a-017d-48c3-b279-61feb0408a78
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-type: external
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homemenuplanner
  template:
    metadata:
      labels:
        app: homemenuplanner
    spec:
      containers:
        - name: homemenuplanner
          image: rmstruthers1/homemenuplanner:latest
          ports:
            - containerPort: 8080
            - containerPort: 443
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: CORS_ALLOWED_ORIGIN
              value: "http://homemenuplanner-frontend.s3-website-us-east-1.amazonaws.com"
            - name: JWT_COOKIE_SECURE
              value: "true"
            - name: JWT_COOKIE_SAME_SITE
              value: "None"
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: jdbc-url
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: username
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: menuplanner-secrets
                  key: jwt-secret
          volumeMounts:
            - name: tls-secret
              mountPath: "/etc/tls"
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: homemenuplanner-tls-secret
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: homemenuplanner-service
spec:
  selector:
    app: homemenuplanner
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
  type: LoadBalancer
