apiVersion: v1
kind: Secret
metadata:
  name: menuplanner-secrets
type: Opaque
data:
  username: REDACTED
  password: REDACTED
  jdbc-url: REDACTED
  jwt-secret: REDACTED
  jwt-cookie-same-site: REDACTED
