INSERT INTO ingredients (name, plural_form) VALUES
-- Vegetables
('Tomato', 'Tomatoes'),
('Grape Tomato', 'Grape Tomatoes'),
('Lettuce', 'Lettuce'),
('Romaine Lettuce', 'Romaine Lettuce'),
('Iceberg Lettuce', 'Iceberg Lettuce'),
('Butterhead Lettuce', 'Butterhead Lettuce'),
('Carrot', 'Carrots'),
('Cucumber', 'Cucumbers'),
('Onion', 'Onions'),
('Red Onion', 'Red Onions'),
('Garlic', 'Garlic Bulbs'),
('Bell Pepper', 'Bell Peppers'),
('Zucchini', 'Zucchinis'),
('Spinach', 'Spinach Leaves'),
('Potato', 'Potatoes'),
('Cabbage', 'Cabbages'),
('Broccoli', 'Broccolis'),
('Cauliflower', 'Cauliflowers'),
('Pea', 'Peas'),
('Radish', 'Radishes'),
('Sweet Potato', 'Sweet Potatoes'),
('Butternut Squash', 'Butternut Squashes'),
('Pumpkin', 'Pumpkins'),
('Beet', 'Beets'),
('Turnip', 'Turnips'),
('Parsnip', 'Parsnips'),
('Celery', 'Celery Stalks'),
('Leek', 'Leeks'),
('Shallot', 'Shallots'),
('Artichoke', 'Artichokes'),
('Mushroom', 'Mushrooms'),
('Asparagus', 'Asparagus Spears'),
('Kale', 'Kale Leaves'),
('Swiss Chard', 'Swiss Chard Leaves'),
('Bok Choy', 'Bok Choy'),
('Brussels Sprout', 'Brussels Sprouts'),
('Green Bean', 'Green Beans'),
('Eggplant', 'Eggplants'),
('Corn', 'Corn Kernels'),

-- Fruits
('Apple', 'Apples'),
('Banana', 'Bananas'),
('Orange', 'Oranges'),
('Lemon', 'Lemons'),
('Lemon Juice', 'Lemon Juice'),
('Lime', 'Limes'),
('Lime Juice', 'Lime Juice'),
('Grape', 'Grapes'),
('Strawberry', 'Strawberries'),
('Blueberry', 'Blueberries'),
('Raspberry', 'Raspberries'),
('Blackberry', 'Blackberries'),
('Kiwi', 'Kiwis'),
('Pineapple', 'Pineapples'),
('Mango', 'Mangos'),
('Peach', 'Peaches'),
('Plum', 'Plums'),
('Apricot', 'Apricots'),
('Nectarine', 'Nectarines'),
('Pomegranate', 'Pomegranates'),
('Coconut', 'Coconuts'),
('Watermelon', 'Watermelons'),
('Honeydew', 'Honeydews'),
('Cantaloupe', 'Cantaloupes'),
('Papaya', 'Papayas'),

-- Oils
('Olive Oil', 'Olive Oil'),
('Canola Oil', 'Canola Oil'),
('Coconut Oil', 'Coconut Oil'),
('Sesame Oil', 'Sesame Oil'),
('Sunflower Oil', 'Sunflower Oil'),
('Grapeseed Oil', 'Grapeseed Oil'),
('Avocado Oil', 'Avocado Oil'),
('Vegetable Oil', 'Vegetable Oil'),

-- Baking Ingredients
('All Purpose Flour', 'All Purpose Flour'),
('Sugar', 'Sugar'),
('Baking Powder', 'Baking Powder'),
('Baking Soda', 'Baking Soda'),
('Yeast', 'Yeast'),
('Butter', 'Butter'),
('Egg', 'Egg'),
('Vanilla Extract', 'Vanilla Extract'),
('Cocoa Powder', 'Cocoa Powder'),
('Cornstarch', 'Cornstarch'),
('Honey', 'Honey'),
('Molasses', 'Molasses'),
('Maple Syrup', 'Maple Syrup'),
('Corn Syrup', 'Corn Syrup'),
('Brown Sugar', 'Brown Sugar'),
('Powdered Sugar', 'Powdered Sugar'),
('Almond Flour', 'Almond Flour'),
('Coconut Flour', 'Coconut Flour'),
('Cake Flour', 'Cake Flour'),
('Pastry Flour', 'Pastry Flour'),
('Rye Flour', 'Rye Flour'),
('Whole Wheat Flour', 'Whole Wheat Flour'),
('Bread Flour', 'Bread Flour'),
('Self-Rising Flour', 'Self-Rising Flour'),
('Pecans', 'Pecans'),
('Walnuts', 'Walnuts'),
('Almonds', 'Almonds'),
('Cashews', 'Cashews'),
('Peanuts', 'Peanuts'),
('Macadamia Nuts', 'Macadamia Nuts'),
('Pistachios', 'Pistachios'),

-- Spices
('Salt', 'Salt'),
('Black Pepper', 'Black Pepper'),
('Cinnamon', 'Cinnamon'),
('Paprika', 'Paprika'),
('Turmeric', 'Turmeric'),
('Cumin', 'Cumin'),
('Coriander', 'Coriander'),
('Ginger', 'Ginger'),
('Nutmeg', 'Nutmeg'),
('Clove', 'Clove'),
('Cardamom', 'Cardamom'),
('Allspice', 'Allspice'),
('Bay Leaf', 'Bay Leaves'),
('Oregano', 'Oregano'),
('Thyme', 'Thyme'),
('Saffron', 'Saffron'),
('Chili Powder', 'Chili Powder'),
('Cayenne Pepper', 'Cayenne Pepper'),
('Smoked Paprika', 'Smoked Paprika'),
('Fennel Seed', 'Fennel Seed'),
('Fenugreek', 'Fenugreek'),
('Mustard Seed', 'Mustard Seed'),
('Caraway Seed', 'Caraway Seed'),
('Curry Powder', 'Curry Powder'),
('Garlic Powder', 'Garlic Powder'),
('Onion Powder', 'Onion Powder'),

-- Meat, Poultry, and Fish
('Chicken Breast', 'Chicken Breast'),
('Boneless Skinless Chicken Breast', 'Boneless Skinless Chicken Breast'),
('Chicken Thigh', 'Chicken Thigh'),
('Beef Steak', 'Beef Steak'),
('Ground Beef', 'Ground Beef'),
('Pork Chop', 'Pork Chop'),
('Pork Shoulder', 'Pork Shoulder'),
('Lamb Chop', 'Lamb Chop'),
('Salmon Fillet', 'Salmon Fillet'),
('Tuna Steak', 'Tuna Steak'),
('Cod Fillet', 'Cod Fillet'),
('Duck Breast', 'Duck Breast'),
('Turkey Breast', 'Turkey Breast'),
('Veal Chop', 'Veal Chop'),
('Venison Steak', 'Venison Steak'),
('Bison Steak', 'Bison Steak'),
('Shrimp', 'Shrimp'),
('Lobster Tail', 'Lobster Tail'),
('Crab Leg', 'Crab Leg'),
('Scallop', 'Scallop'),
('Clam', 'Clam'),
('Oyster', 'Oyster'),

-- Legumes and Grains
('Rice', 'Rice'),
('White Rice', 'White Rice'),
('Brown Rice', 'Brown Rice'),
('Basmati Rice', 'Basmati Rice'),
('Jasmine Rice', 'Jasmine Rice'),
('Wild Rice', 'Wild Rice'),
('Arborio Rice', 'Arborio Rice'),
('Sticky Rice', 'Sticky Rice'),
('Sushi Rice', 'Sushi Rice'),
('Quinoa', 'Quinoa'),
('Lentil', 'Lentil'),
('Red Lentil', 'Red Lentil'),
('Green Lentil', 'Green Lentil'),
('Black Bean', 'Black Bean'),
('Pinto Bean', 'Pinto Bean'),
('Kidney Bean', 'Kidney Bean'),
('Navy Bean', 'Navy Bean'),
('Chickpea', 'Chickpea'),
('Adzuki Bean', 'Adzuki Bean'),
('Cannellini Bean', 'Cannellini Bean'),
('Great Northern Bean', 'Great Northern Bean'),
('Mung Bean', 'Mung Bean'),
('Lima Bean', 'Lima Bean'),
('Split Pea', 'Split Pea'),
('Oat', 'Oat'),
('Cornmeal', 'Cornmeal'),
('Barley', 'Barley'),
('Farro', 'Farro'),
('Bulgur', 'Bulgur'),
('Millet', 'Millet'),
('Teff', 'Teff'),

-- Pasta
('Spaghetti', 'Spaghetti'),
('Fettuccine', 'Fettuccine'),
('Penne', 'Penne'),
('Macaroni', 'Macaroni'),
('Fusilli', 'Fusilli'),
('Linguine', 'Linguine'),
('Rigatoni', 'Rigatoni'),
('Orzo', 'Orzo'),
('Rotini', 'Rotini'),
('Cavatappi', 'Cavatappi'),
('Lasagna', 'Lasagna'),
('Shell Pasta', 'Shell Pasta'),
('Bucatini', 'Bucatini'),
('Angel Hair Pasta', 'Angel Hair Pasta'),
('Gemelli', 'Gemelli'),
('Cannelloni', 'Cannelloni'),


-- Dairy and Cheeses
('Milk', 'Milk'),
('Yogurt', 'Yogurt'),
('Cheese', 'Cheese'),
('Cream', 'Cream'),
('Sour Cream', 'Sour Cream'),
('Ghee', 'Ghee'),
('Cheddar Cheese', 'Cheddar Cheese'),
('Mozzarella Cheese', 'Mozzarella Cheese'),
('Parmesan Cheese', 'Parmesan Cheese'),
('Gouda Cheese', 'Gouda Cheese'),
('Swiss Cheese', 'Swiss Cheese'),
('Brie Cheese', 'Brie Cheese'),
('Camembert Cheese', 'Camembert Cheese'),
('Blue Cheese', 'Blue Cheese'),
('Feta Cheese', 'Feta Cheese'),
('Goat Cheese', 'Goat Cheese'),
('Cotija Cheese', 'Cotija Cheese'),
('Monterey Jack Cheese', 'Monterey Jack Cheese'),
('Pepper Jack Cheese', 'Pepper Jack Cheese'),
('Provolone Cheese', 'Provolone Cheese'),
('Ricotta Cheese', 'Ricotta Cheese'),
('Mascarpone Cheese', 'Mascarpone Cheese'),
('Cream Cheese', 'Cream Cheese'),

-- Sauces and Condiments
('Ketchup', 'Ketchup'),
('Mustard', 'Mustard'),
('Mayonnaise', 'Mayonnaise'),
('Soy Sauce', 'Soy Sauce'),
('Hot Sauce', 'Hot Sauce'),
('Salsa', 'Salsa'),
('Tahini', 'Tahini'),
('Hummus', 'Hummus'),
('Pesto', 'Pesto'),
('Chutney', 'Chutney'),
('Relish', 'Relish'),
('Pickle', 'Pickle'),
('Barbecue Sauce', 'Barbecue Sauce'),
('Worcestershire Sauce', 'Worcestershire Sauce'),
('Fish Sauce', 'Fish Sauce'),
('Oyster Sauce', 'Oyster Sauce'),
('Sriracha', 'Sriracha'),

-- Other Ingredients
('Tofu', 'Tofu'),
('Tempeh', 'Tempeh'),
('Seitan', 'Seitan'),
('Edamame', 'Edamame'),
('Coconut Milk', 'Coconut Milk'),
('Coconut Water', 'Coconut Water'),
('Rice Paper', 'Rice Paper'),
('Seaweed', 'Seaweed'),
('Nori', 'Nori'),
('Miso', 'Miso'),
('Kimchi', 'Kimchi'),
('Sauerkraut', 'Sauerkraut'),
('Wasabi', 'Wasabi'),
('Tamarind', 'Tamarind'),
('Tapioca', 'Tapioca'),
('Arrowroot', 'Arrowroot'),
('Agar-Agar', 'Agar-Agar'),
('Gelatin', 'Gelatin'),
('Xanthan Gum', 'Xanthan Gum'),
('Pectin', 'Pectin'),
('Guar Gum', 'Guar Gum'),
('Sorghum', 'Sorghum'),
('Amaranth', 'Amaranth'),
('Buckwheat', 'Buckwheat'),
('Chia Seed', 'Chia Seed'),
('Flaxseed', 'Flaxseed'),
('Sesame Seed', 'Sesame Seed'),
('Hemp Seed', 'Hemp Seed')
;
